package com.example.model;
// Generated Apr 7, 2023, 3:25:04 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer carId;
	private CarType carType;
	private String carName;
	private String description;
	private double pricePerDay;
	private String color;
	private String platNumber;
	@JsonIgnore
	private Set reservations = new HashSet(0);

	public Car() {
	}

	public Car(CarType carType, String carName, String description, double pricePerDay, String color,
			String platNumber) {
		this.carType = carType;
		this.carName = carName;
		this.description = description;
		this.pricePerDay = pricePerDay;
		this.color = color;
		this.platNumber = platNumber;
	}

	public Car(CarType carType, String carName, String description, double pricePerDay, String color, String platNumber,
			Set reservations) {
		this.carType = carType;
		this.carName = carName;
		this.description = description;
		this.pricePerDay = pricePerDay;
		this.color = color;
		this.platNumber = platNumber;
		this.reservations = reservations;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public CarType getCarType() {
		return this.carType;
	}

	public void setCarType(CarType carType) {
		this.carType = carType;
	}

	public String getCarName() {
		return this.carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getPricePerDay() {
		return this.pricePerDay;
	}

	public void setPricePerDay(double pricePerDay) {
		this.pricePerDay = pricePerDay;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getPlatNumber() {
		return this.platNumber;
	}

	public void setPlatNumber(String platNumber) {
		this.platNumber = platNumber;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
