package com.example.model;
// Generated Apr 7, 2023, 3:25:04 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private String userUsername;
	private String userPassword;
	private String userFirstname;
	private String userSurname;
	private String userPhonenumber;
	private String userType;
	private Set reservations = new HashSet(0);

	public Users() {
	}

	public Users(String userUsername, String userPassword, String userFirstname, String userSurname,
			String userPhonenumber, String userType) {
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userSurname = userSurname;
		this.userPhonenumber = userPhonenumber;
		this.userType = userType;
	}

	public Users(String userUsername, String userPassword, String userFirstname, String userSurname,
			String userPhonenumber, String userType, Set reservations) {
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userSurname = userSurname;
		this.userPhonenumber = userPhonenumber;
		this.userType = userType;
		this.reservations = reservations;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserFirstname() {
		return this.userFirstname;
	}

	public void setUserFirstname(String userFirstname) {
		this.userFirstname = userFirstname;
	}

	public String getUserSurname() {
		return this.userSurname;
	}

	public void setUserSurname(String userSurname) {
		this.userSurname = userSurname;
	}

	public String getUserPhonenumber() {
		return this.userPhonenumber;
	}

	public void setUserPhonenumber(String userPhonenumber) {
		this.userPhonenumber = userPhonenumber;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
